export enum CatalogueTypeEnum {
  BLOOD_TYPE = 'BLOOD_TYPE',
  ETHNIC_ORIGIN = 'ETHNIC_ORIGIN',
  IDENTIFICATION_TYPE = 'IDENTIFICATION_TYPE',
  GENDER = 'GENDER',
  MARITAL_STATUS = 'MARITAL_STATUS',
  SEX = 'SEX',
}

export enum CatalogueStateEnum {
  ACTIVE = 'ACTIVE',
}
