export enum AuthRepositoryEnum {
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY',
}

export enum CoreRepositoryEnum {
  CAREER_REPOSITORY = 'CAREER_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  CURRICULUM_REPOSITORY = 'CURRICULUM_REPOSITORY',
  INFORMATION_STUDENT_REPOSITORY = 'INFORMATION_STUDENT_REPOSITORY',
  INFORMATION_TEACHER_REPOSITORY = 'INFORMATION_TEACHER_REPOSITORY',
  INSTITUTION_REPOSITORY = 'INSTITUTION_REPOSITORY',
  STUDENT_REPOSITORY = 'STUDENT_REPOSITORY',
  SUBJECT_REPOSITORY = 'SUBJECT_REPOSITORY',
  TEACHER_REPOSITORY = 'TEACHER_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  SCHOOL_PERIOD_REPOSITORY = 'SCHOOL_PERIOD_REPOSITORY',
  EVENT_REPOSITORY = 'EVENT_REPOSITORY',
}

export enum CommonRepositoryEnum {
  FILE_REPOSITORY = 'FILE_REPOSITORY',
}
