export enum AuthRepositoryEnum {
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY',
}

export enum CoreRepositoryEnum {
  ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY',
  ATTENDANCE_REPOSITORY = 'ATTENDANCE_REPOSITORY',
  CAREER_REPOSITORY = 'CAREER_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  CLASSROOM_REPOSITORY = 'CLASSROOM_REPOSITORY',
  CURRICULUM_REPOSITORY = 'CURRICULUM_REPOSITORY',
  ENROLLMENT_DETAIL_REPOSITORY = 'ENROLLMENT_DETAIL_REPOSITORY',
  ENROLLMENT_REPOSITORY = 'ENROLLMENT_REPOSITORY',
  EVENT_REPOSITORY = 'EVENT_REPOSITORY',
  EXPORT_REPOSITORY = 'EXPORT_REPOSITORY',
  GRADE_REPOSITORY = 'GRADE_REPOSITORY',
  IMPORT_REPOSITORY = 'IMPORT_REPOSITORY',
  INFORMATION_STUDENT_REPOSITORY = 'INFORMATION_STUDENT_REPOSITORY',
  INFORMATION_TEACHER_REPOSITORY = 'INFORMATION_TEACHER_REPOSITORY',
  INSTITUTION_REPOSITORY = 'INSTITUTION_REPOSITORY',
  LOCATION_REPOSITORY = 'LOCATION_REPOSITORY',
  PARTIAL_PERMISSION_REPOSITORY = 'PARTIAL_PERMISSION_REPOSITORY',
  PARTIAL_REPOSITORY = 'PARTIAL_REPOSITORY',
  SCHEDULE_REPOSITORY = 'SCHEDULE_REPOSITORY',
  SCHOOL_PERIOD_REPOSITORY = 'SCHOOL_PERIOD_REPOSITORY',
  STUDENT_REPOSITORY = 'STUDENT_REPOSITORY',
  SUBJECT_REQUIREMENT_REPOSITORY = 'SUBJECT_REQUIREMENT_REPOSITORY',
  SUBJECT_REPOSITORY = 'SUBJECT_REPOSITORY',
  TEACHER_DISTRIBUTION_REPOSITORY = 'TEACHER_DISTRIBUTION_REPOSITORY',
  TEACHER_REPOSITORY = 'TEACHER_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
}

export enum CommonRepositoryEnum {
  FILE_REPOSITORY = 'FILE_REPOSITORY',
}
