import {Global, Module} from '@nestjs/common';
import {CacheModule} from '@nestjs/cache-manager';
import {
    CareersController,
    CataloguesController,
    CurriculumsController,
    EnrollmentDetailsController,
    EnrollmentsController,
    EventsController,
    ExportsController,
    ImportsController,
    InformationStudentsController,
    InformationTeachersController,
    InstitutionsController,
    PDFController,
    SchoolPeriodsController,
    SecretaryController,
    StudentsController,
    SubjectsController,
    TeacherDistributionsController,
    TeachersController,
} from '@core/controllers';
import {
    AddressesService,
    AttendancesService,
    CareerAcademicPeriodsService,
    CareersService,
    CataloguesService,
    ClassroomsService,
    CurriculumsService,
    EnrollmentsDetailService,
    EnrollmentsService,
    EventsService,
    ExportsService,
    GradesService,
    ImportsService,
    InformationStudentsService,
    InformationTeachersService,
    InstitutionsService,
    LocationsService,
    PartialsService,
    PDFNotas,
    PDFService,
    SchoolPeriodsService,
    SecretaryService,
    StudentsService, SubjectCorequisitesService,
    SubjectPrerequisitesService,
    SubjectsService,
    TeacherDistributionsService,
    TeachersService,
} from '@core/services';
import {DatabaseModule} from '@database';
import {coreProviders} from '@core/providers';
import {VerifyUserMiddleware} from "../../middlewares/verify-user.middleware";

@Global()
@Module({
    imports: [DatabaseModule, CacheModule.register()],
    controllers: [
        CareersController,
        CataloguesController,
        CurriculumsController,
        EventsController,
        ExportsController,
        ImportsController,
        InformationStudentsController,
        InformationTeachersController,
        InstitutionsController,
        SchoolPeriodsController,
        StudentsController,
        SubjectsController,
        TeachersController,
        TeacherDistributionsController,
        PDFController,
        EnrollmentsController,
        EnrollmentDetailsController,
        SecretaryController
    ],
    providers: [
        ...coreProviders,
        AttendancesService,
        CareersService,
        CareerAcademicPeriodsService,
        CataloguesService,
        CurriculumsService,
        EventsService,
        ExportsService,
        ImportsService,
        TeachersService,
        InformationStudentsService,
        InformationTeachersService,
        InstitutionsService,
        LocationsService,
        PartialsService,
        SchoolPeriodsService,
        StudentsService,
        SubjectsService,
        SubjectPrerequisitesService,
        SubjectCorequisitesService,
        EnrollmentsDetailService,
        EnrollmentsService,
        ClassroomsService,
        GradesService,
        TeacherDistributionsService,
        PDFService,
        PDFNotas,
        SecretaryService,
    ],
    exports: [
        ...coreProviders,
        AttendancesService,
        CareersService,
        CareerAcademicPeriodsService,
        CataloguesService,
        CurriculumsService,
        EventsService,
        ExportsService,
        ImportsService,
        InformationStudentsService,
        InformationTeachersService,
        InstitutionsService,
        LocationsService,
        PartialsService,
        SchoolPeriodsService,
        StudentsService,
        SubjectsService,
        SubjectPrerequisitesService,
        SubjectCorequisitesService,
        TeachersService,
        EnrollmentsDetailService,
        EnrollmentsService,
        ClassroomsService,
        GradesService,
        TeacherDistributionsService,
        PDFService,
        PDFNotas,
        SecretaryService,
    ],
})
export class CoreModule {

}
